---
apiVersion: v1
metadata:
  name: ccb-app
  namespace: default
kind: Pod
spec:
  containers:
    - name: ccb-web
      image:  busybox
      command: ["/bin/sh","-c","env"]
      env:
        - name: WHICH_SCHOOL
          valueFrom:
            configMapKeyRef:
              name: my-app
              key: school
