apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    env: tst
    app: nginx
    type: appserver
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    environment: test
