apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: default
spec:
  containers:
  - name: tomcat
    image: docker.io/tomcat
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
